import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../Components/banner'
import Characters from '../Components/characters'
import Bottom from '../Components/bottom'
import Footer from '../Components/footer'
const smallLogo = require('../Components/assets/banner-logo-small.gif')

export default function Home({data}) {
  return (
    <div className="">
      <Head className="ma0 pa0 mb0">
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/tachyons@4.12.0/css/tachyons.min.css"/>
      </Head>

      <header className="ma0 pa0" >
        <nav className="fixed w-100 pa4 ma0 h2 top-0 z-1 flex items-center justify-between" style={{ backgroundColor: "#5055"}}>
          <div className="">
            <div className="flex">
              <Image src={smallLogo} width={60}/>
              <p>5 Force Fighters</p>
            </div>
          </div>
          <p className="">=</p>
        </nav>
      </header>
      
      <main className="ma0 pa0">
        <Banner/>
        <Characters/>
        <Bottom />
      </main>

      <footer className={styles.footer}>
        <Footer />
     
      </footer>
    </div>
  )
}




/*f
export async function getData() {
  const res = await fetch('http://127.0.0.1:8090/api/collections/test/records/page=1&perPage=30')
  const data = await res.json();
  console.log(data)
  return {
    props: {
      data: data
    }
  }
}

etch('/api/route-name', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify(objectWithData),
}) */